# Generated by Django 5.1.1 on 2024-09-27 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('chapters', '0003_remove_subchapter_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='category.category'),
        ),
    ]
