# Generated by Django 5.1.1 on 2024-09-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_usrinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usrinfo',
            options={'verbose_name': 'Admin info', 'verbose_name_plural': "Admin info's"},
        ),
        migrations.AddField(
            model_name='usrinfo',
            name='map_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usrinfo',
            name='map_link',
            field=models.URLField(null=True),
        ),
    ]
