# Generated by Django 5.1.1 on 2024-09-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_usrinfo_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='map_link',
            field=models.TextField(help_text='e.g: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d9383............s!4v1725949416258!5m2!1sen!2s', max_length=400, null=True),
        ),
    ]
