# Generated by Django 5.1.1 on 2024-09-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_usrinfo_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrinfo',
            name='map_link',
            field=models.TextField(help_text='Size: 1000 x 450 for embeded map', max_length=400, null=True),
        ),
    ]
