# Generated by Django 5.1.1 on 2024-09-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_new_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='new_slug',
            new_name='slug',
        ),
    ]
