# Generated by Django 5.1.1 on 2024-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carosel', '0002_alter_carousel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(help_text='Image size 1280 x 719 only', upload_to='carosel'),
        ),
    ]
