# Generated by Django 5.1.1 on 2024-09-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subjects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='image',
            field=models.ImageField(help_text='Image size 800 x 800 only', null=True, upload_to='subjects'),
        ),
    ]
