# Generated by Django 5.1.1 on 2024-09-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subjects_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='class_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
