# Generated by Django 5.1.1 on 2024-09-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_subjects_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='class_name',
        ),
    ]
