# Generated by Django 5.1.1 on 2024-09-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_subjects_subject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subject_description',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subject_name',
            field=models.CharField(max_length=10),
        ),
    ]
