# Generated by Django 5.1.1 on 2024-09-26 06:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_alter_subjects_subject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='new_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='subject_name', unique=True),
        ),
    ]
