# Generated by Django 5.1.1 on 2024-09-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_subjects_new_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='new_slug',
            new_name='slug',
        ),
    ]
