# Generated by Django 5.1.1 on 2024-09-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
