# Generated by Django 5.1.1 on 2024-09-26 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_url'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='url',
        ),
        migrations.AddField(
            model_name='card',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
