# Generated by Django 5.1.1 on 2024-09-26 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_card_url_card_catagory'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='catagory',
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
    ]
