# Generated by Django 5.1.1 on 2024-09-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_card_catagory_card_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(max_length=74),
        ),
    ]
