# Generated by Django 5.1.1 on 2024-09-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_alter_card_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(help_text='max 75 characters', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(help_text='max 16 characters', max_length=16),
        ),
    ]
